[package]
name = "linfa"
version = "0.1.0"
authors = ["LukeMathWalker <lucapalmieri1993@hotmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
ndarray = "0.12.1"
ndarray-rand = "0.9.0"
rand = "*"
derive_more = "0.13.0"
